title: MochiMemo
description: my project
author: 林晚晚ss.
logo: path/to/logo.png

content:
  local:
    enabled: true
    postsDir: contents/posts
    pagesDir: contents/pages
  git:
    enabled:
    platform: github
    owner: your-name
    repo: your-repo
    labels:
      post: post
      page: page

routes:
  - path: /about
    name: 关于
    file: pages/about.md
  - path: /welcome
    name: 欢迎
    issue:
      slug: welcome
  - path: /links
    name: 友链
    issue:
      label: page:links
  - path: /old
    name: 老东西
    issue:
      number: 3

theme: default
plugins:
  - name: seo
    enabled:
    options:

themeConfig:
  leftnav:
    selfDescription: 你所love的，就是你的live
    pos: 二相乐园
    work: 姬霓太美
    school: 绘世学院
    email: 114514@unknown.oiiai
    avatar:
    contacts:
      github:
      bilibili:
      wechat:
      qq:
  header:
    links:
      - name: 首页
        url: /
      - name: 文章
        url: /posts
      - name: 分类
        url: /categories
      - name: 标签
        url: /tags
  footer:
    startYear: 2026
    ICP:
      detail:
      url:
      ico:
    GAB:
      detail:
      url:
      ico:
  tags:
    - name: test
      thumb:
  category:
    - name: 技术
      thumb:
    - name: 随笔
      thumb:
  backgroundImage: https://api.imlazy.ink/img
  wapBackgroundImage: https://api.imlazy.ink/img-phone